2024-04-13 16:11:31,706 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Sat, 13 Apr 2024 16:11:31 +0000. Up 6.36 seconds.
2024-04-13 16:11:31,706 - main.py[DEBUG]: No kernel command line url found.
2024-04-13 16:11:31,706 - main.py[DEBUG]: Closing stdin.
2024-04-13 16:11:31,707 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2024-04-13 16:11:31,716 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-04-13 16:11:31,725 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2024-04-13 16:11:31,736 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-04-13 16:11:31,741 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2024-04-13 16:11:31,742 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-04-13 16:11:31,759 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2024-04-13 16:11:31,760 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-04-13 16:11:31,778 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2024-04-13 16:11:31,779 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-04-13 16:11:31,799 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2024-04-13 16:11:31,800 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-04-13 16:11:31,826 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2024-04-13 16:11:31,826 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-04-13 16:11:31,852 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2024-04-13 16:11:31,853 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-04-13 16:11:31,881 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2024-04-13 16:11:31,882 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-04-13 16:11:31,911 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2024-04-13 16:11:31,912 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2024-04-13 16:11:31,912 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2024-04-13 16:11:31,913 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2024-04-13 16:11:31,914 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2024-04-13 16:11:31,926 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-04-13 16:11:31,927 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-04-13 16:11:31,927 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2024-04-13 16:11:31,928 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2024-04-13 16:11:31,929 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-04-13 16:11:31,930 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-04-13 16:11:31,930 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:31,935 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:31,946 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2024-04-13 16:11:31,957 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2024-04-13 16:11:31,957 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2024-04-13 16:11:31,958 - stages.py[DEBUG]: no cache found
2024-04-13 16:11:31,958 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2024-04-13 16:11:31,958 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-04-13 16:11:31,968 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-04-13 16:11:31,968 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2024-04-13 16:11:31,977 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2024-04-13 16:11:31,984 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2024-04-13 16:11:32,000 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2024-04-13 16:11:32,007 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-04-13 16:11:32,011 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2024-04-13 16:11:32,012 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2024-04-13 16:11:32,013 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2024-04-13 16:11:32,013 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2024-04-13 16:11:32,013 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2024-04-13 16:11:32,013 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2024-04-13 16:11:32,015 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2024-04-13 16:11:32,015 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2024-04-13 16:11:32,015 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2024-04-13 16:11:32,015 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2024-04-13 16:11:32,015 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2024-04-13 16:11:32,026 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-04-13 16:11:32,047 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2024-04-13 16:11:32,047 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2024-04-13 16:11:32,047 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,056 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-04-13 16:11:32,056 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2024-04-13 16:11:32,057 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,067 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2513b) after 1 attempts
2024-04-13 16:11:32,067 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,070 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2024-04-13 16:11:32,070 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,076 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2024-04-13 16:11:32,077 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,079 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2024-04-13 16:11:32,079 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,081 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2024-04-13 16:11:32,081 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,086 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2024-04-13 16:11:32,087 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,089 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2024-04-13 16:11:32,089 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,091 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2024-04-13 16:11:32,091 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,096 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2024-04-13 16:11:32,097 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,099 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2024-04-13 16:11:32,099 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,101 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 210b) after 1 attempts
2024-04-13 16:11:32,101 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,106 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2024-04-13 16:11:32,107 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,109 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2024-04-13 16:11:32,109 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,111 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2024-04-13 16:11:32,111 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,116 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2024-04-13 16:11:32,117 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,119 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2024-04-13 16:11:32,119 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,121 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2024-04-13 16:11:32,121 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,126 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2024-04-13 16:11:32,127 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,129 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2024-04-13 16:11:32,129 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,131 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/ (200, 230b) after 1 attempts
2024-04-13 16:11:32,131 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,137 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/ipv4-associations/ (200, 13b) after 1 attempts
2024-04-13 16:11:32,137 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/ipv4-associations/18.192.182.43' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/ipv4-associations/18.192.182.43', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,139 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/ipv4-associations/18.192.182.43 (200, 11b) after 1 attempts
2024-04-13 16:11:32,140 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,142 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/device-number (200, 1b) after 1 attempts
2024-04-13 16:11:32,142 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,145 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/interface-id (200, 21b) after 1 attempts
2024-04-13 16:11:32,145 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,157 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/local-hostname (200, 44b) after 1 attempts
2024-04-13 16:11:32,157 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,159 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/local-ipv4s (200, 11b) after 1 attempts
2024-04-13 16:11:32,159 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,162 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/mac (200, 17b) after 1 attempts
2024-04-13 16:11:32,162 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,166 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/owner-id (200, 12b) after 1 attempts
2024-04-13 16:11:32,167 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,169 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/public-hostname (200, 52b) after 1 attempts
2024-04-13 16:11:32,169 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,171 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/public-ipv4s (200, 13b) after 1 attempts
2024-04-13 16:11:32,171 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,176 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/security-group-ids (200, 20b) after 1 attempts
2024-04-13 16:11:32,177 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,186 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/security-groups (200, 56b) after 1 attempts
2024-04-13 16:11:32,187 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,197 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/subnet-id (200, 24b) after 1 attempts
2024-04-13 16:11:32,197 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,207 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/subnet-ipv4-cidr-block (200, 13b) after 1 attempts
2024-04-13 16:11:32,207 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,209 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-id (200, 21b) after 1 attempts
2024-04-13 16:11:32,209 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,211 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2024-04-13 16:11:32,212 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,216 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/0a:1e:ed:98:92:8f/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2024-04-13 16:11:32,217 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,219 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2024-04-13 16:11:32,219 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,221 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 13b) after 1 attempts
2024-04-13 16:11:32,221 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,226 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2024-04-13 16:11:32,227 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,229 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 12b) after 1 attempts
2024-04-13 16:11:32,229 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,231 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2024-04-13 16:11:32,231 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,236 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2024-04-13 16:11:32,237 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,239 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2024-04-13 16:11:32,239 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,241 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2024-04-13 16:11:32,241 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,246 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2024-04-13 16:11:32,247 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,249 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2024-04-13 16:11:32,249 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,251 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 44b) after 1 attempts
2024-04-13 16:11:32,251 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,253 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2024-04-13 16:11:32,254 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,267 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-04-13 16:11:32,267 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,269 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2024-04-13 16:11:32,269 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,271 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2024-04-13 16:11:32,272 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,276 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 44b) after 1 attempts
2024-04-13 16:11:32,277 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,279 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 11b) after 1 attempts
2024-04-13 16:11:32,279 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,281 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2024-04-13 16:11:32,281 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,283 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2024-04-13 16:11:32,284 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,287 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 52b) after 1 attempts
2024-04-13 16:11:32,287 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,296 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2024-04-13 16:11:32,297 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,309 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2024-04-13 16:11:32,309 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,316 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2024-04-13 16:11:32,317 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,326 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2024-04-13 16:11:32,327 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,329 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 481b) after 1 attempts
2024-04-13 16:11:32,329 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,332 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1171b) after 1 attempts
2024-04-13 16:11:32,332 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,337 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1491b) after 1 attempts
2024-04-13 16:11:32,337 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-04-13 16:11:32,339 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2024-04-13 16:11:32,339 - util.py[DEBUG]: Crawl of metadata service took 0.325 seconds
2024-04-13 16:11:32,343 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2024-04-13 16:11:32,344 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-04-13 16:11:32,344 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-04-13 16:11:32,345 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2024-04-13 16:11:32,346 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp5xk4w05u) - w: [600] 12039 bytes/chars
2024-04-13 16:11:32,347 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpe2fmda3m) - w: [644] 7897 bytes/chars
2024-04-13 16:11:32,347 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2024-04-13 16:11:32,347 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2024-04-13 16:11:32,348 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-04-13 16:11:32,348 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-04-13 16:11:32,348 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,371 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-04-13 16:11:32,371 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-04-13 16:11:32,371 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,373 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-04-13 16:11:32,373 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-04-13 16:11:32,373 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,386 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-04-13 16:11:32,386 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-04-13 16:11:32,386 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,391 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-04-13 16:11:32,392 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-04-13 16:11:32,392 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,394 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-04-13 16:11:32,394 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,394 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-04-13 16:11:32,395 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-04-13 16:11:32,395 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-05efeb4cc0bcba815'
2024-04-13 16:11:32,396 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815 (recursive=True)
2024-04-13 16:11:32,401 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/handlers (recursive=False)
2024-04-13 16:11:32,402 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815 (recursive=True)
2024-04-13 16:11:32,418 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/scripts (recursive=False)
2024-04-13 16:11:32,419 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815 (recursive=True)
2024-04-13 16:11:32,438 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem (recursive=False)
2024-04-13 16:11:32,438 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-05efeb4cc0bcba815/datasource (quiet=False)
2024-04-13 16:11:32,438 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/datasource - wb: [644] 29 bytes
2024-04-13 16:11:32,439 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/datasource (recursive=False)
2024-04-13 16:11:32,440 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/datasource (recursive=False)
2024-04-13 16:11:32,441 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2024-04-13 16:11:32,441 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-04-13 16:11:32,442 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-04-13 16:11:32,443 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2024-04-13 16:11:32,443 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2024-04-13 16:11:32,443 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2024-04-13 16:11:32,443 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-04-13 16:11:32,444 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-04-13 16:11:32,445 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2024-04-13 16:11:32,445 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-04-13 16:11:32,446 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-04-13 16:11:32,446 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2024-04-13 16:11:32,447 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-04-13 16:11:32,448 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-04-13 16:11:32,449 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12660 bytes
2024-04-13 16:11:32,450 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/obj.pkl (recursive=False)
2024-04-13 16:11:32,451 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/obj.pkl (recursive=False)
2024-04-13 16:11:32,451 - main.py[DEBUG]: [net] init will now be targeting instance id: i-05efeb4cc0bcba815. new=True
2024-04-13 16:11:32,451 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-04-13 16:11:32,451 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-04-13 16:11:32,452 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,475 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-04-13 16:11:32,475 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-04-13 16:11:32,475 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,476 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-04-13 16:11:32,477 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-04-13 16:11:32,477 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,479 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-04-13 16:11:32,479 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-04-13 16:11:32,480 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,485 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-04-13 16:11:32,485 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-04-13 16:11:32,496 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,498 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-04-13 16:11:32,498 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,498 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-04-13 16:11:32,500 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-04-13 16:11:32,500 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-04-13 16:11:32,500 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-04-13 16:11:32,500 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-04-13 16:11:32,500 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2024-04-13 16:11:32,500 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2024-04-13 16:11:32,500 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-04-13 16:11:32,500 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-04-13 16:11:32,501 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2024-04-13 16:11:32,501 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2024-04-13 16:11:32,501 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2024-04-13 16:11:32,501 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2024-04-13 16:11:32,501 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2024-04-13 16:11:32,501 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2024-04-13 16:11:32,501 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-04-13 16:11:32,501 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-04-13 16:11:32,501 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2024-04-13 16:11:32,501 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2024-04-13 16:11:32,501 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2024-04-13 16:11:32,501 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2024-04-13 16:11:32,501 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2024-04-13 16:11:32,502 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2024-04-13 16:11:32,502 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-04-13 16:11:32,502 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-04-13 16:11:32,502 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2024-04-13 16:11:32,502 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2024-04-13 16:11:32,502 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2024-04-13 16:11:32,502 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2024-04-13 16:11:32,502 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2024-04-13 16:11:32,502 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2024-04-13 16:11:32,502 - stages.py[DEBUG]: network config disabled by system_cfg
2024-04-13 16:11:32,502 - stages.py[INFO]: network config is disabled by system_cfg
2024-04-13 16:11:32,502 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2024-04-13 16:11:32,502 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2024-04-13 16:11:32,503 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/user-data.txt - wb: [600] 2513 bytes
2024-04-13 16:11:32,503 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/user-data.txt (recursive=False)
2024-04-13 16:11:32,504 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/user-data.txt (recursive=False)
2024-04-13 16:11:32,506 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,510 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/user-data.txt.i - wb: [600] 2535 bytes
2024-04-13 16:11:32,511 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/user-data.txt.i (recursive=False)
2024-04-13 16:11:32,512 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/user-data.txt.i (recursive=False)
2024-04-13 16:11:32,513 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data.txt - wb: [600] 0 bytes
2024-04-13 16:11:32,513 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data.txt (recursive=False)
2024-04-13 16:11:32,514 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data.txt (recursive=False)
2024-04-13 16:11:32,516 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data.txt.i - wb: [600] 308 bytes
2024-04-13 16:11:32,517 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data.txt.i (recursive=False)
2024-04-13 16:11:32,518 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data.txt.i (recursive=False)
2024-04-13 16:11:32,518 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data2.txt - wb: [600] 0 bytes
2024-04-13 16:11:32,519 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data2.txt (recursive=False)
2024-04-13 16:11:32,520 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data2.txt (recursive=False)
2024-04-13 16:11:32,521 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data2.txt.i - wb: [600] 308 bytes
2024-04-13 16:11:32,522 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data2.txt.i (recursive=False)
2024-04-13 16:11:32,523 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/vendor-data2.txt.i (recursive=False)
2024-04-13 16:11:32,524 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-04-13 16:11:32,525 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-9-28.eu-central-1.compute.internal (ip-172-31-9-28)
2024-04-13 16:11:32,536 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-9-28.eu-central-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:32,701 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-9-28.eu-central-1.compute.internal
2024-04-13 16:11:32,702 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-9-28.eu-central-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:32,707 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpqb8xnotj) - w: [644] 91 bytes/chars
2024-04-13 16:11:32,708 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/consume_data - wb: [644] 24 bytes
2024-04-13 16:11:32,709 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/consume_data (recursive=False)
2024-04-13 16:11:32,711 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/consume_data (recursive=False)
2024-04-13 16:11:32,711 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/consume_data'>)
2024-04-13 16:11:32,712 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2024-04-13 16:11:32,712 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2024-04-13 16:11:32,713 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2024-04-13 16:11:32,713 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2024-04-13 16:11:32,713 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2024-04-13 16:11:32,713 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2024-04-13 16:11:32,713 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2024-04-13 16:11:32,713 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2024-04-13 16:11:32,713 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2024-04-13 16:11:32,713 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2024-04-13 16:11:32,713 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,714 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,714 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,714 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,714 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,714 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2024-04-13 16:11:32,714 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2024-04-13 16:11:32,714 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2024-04-13 16:11:32,714 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,726 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2024-04-13 16:11:32,726 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2024-04-13 16:11:32,726 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2024-04-13 16:11:32,726 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1864 bytes
2024-04-13 16:11:32,727 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/scripts/user-data.txt (recursive=False)
2024-04-13 16:11:32,728 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/scripts/user-data.txt (recursive=False)
2024-04-13 16:11:32,729 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2024-04-13 16:11:32,730 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/cloud-config.txt - wb: [600] 154 bytes
2024-04-13 16:11:32,731 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/cloud-config.txt (recursive=False)
2024-04-13 16:11:32,732 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/cloud-config.txt (recursive=False)
2024-04-13 16:11:32,732 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,732 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,732 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,732 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,732 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2024-04-13 16:11:32,732 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2024-04-13 16:11:32,733 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2024-04-13 16:11:32,733 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2024-04-13 16:11:32,733 - stages.py[DEBUG]: no vendordata from datasource
2024-04-13 16:11:32,733 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2024-04-13 16:11:32,733 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2024-04-13 16:11:32,733 - stages.py[DEBUG]: no vendordata2 from datasource
2024-04-13 16:11:32,733 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2024-04-13 16:11:32,733 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-04-13 16:11:32,733 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-04-13 16:11:32,733 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,770 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-04-13 16:11:32,770 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-04-13 16:11:32,770 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,772 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-04-13 16:11:32,772 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-04-13 16:11:32,772 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,775 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-04-13 16:11:32,775 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-04-13 16:11:32,775 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,792 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-04-13 16:11:32,792 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-04-13 16:11:32,792 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,795 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-04-13 16:11:32,795 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,795 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-04-13 16:11:32,806 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-04-13 16:11:32,806 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-04-13 16:11:32,806 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,809 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:32,809 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:32,930 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-04-13 16:11:32,930 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-04-13 16:11:32,930 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-04-13 16:11:32,946 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2024-04-13 16:11:32,947 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16872 bytes
2024-04-13 16:11:32,962 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/obj.pkl (recursive=False)
2024-04-13 16:11:32,963 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/obj.pkl (recursive=False)
2024-04-13 16:11:32,964 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2024-04-13 16:11:32,964 - main.py[DEBUG]: no di_report found in config.
2024-04-13 16:11:32,976 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:32,976 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:32,980 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:32,980 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:32,986 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:32,986 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:32,989 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:32,989 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:32,992 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:32,992 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,007 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,007 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,012 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,013 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,016 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,016 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,026 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,026 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,030 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,030 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,032 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,033 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,035 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,035 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,046 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,046 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,050 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,050 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,053 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,054 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,064 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:33,064 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:33,067 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-04-13 16:11:33,068 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2024-04-13 16:11:33,068 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2024-04-13 16:11:33,068 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7efce5f35d00>)
2024-04-13 16:11:33,069 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2024-04-13 16:11:33,069 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2024-04-13 16:11:33,069 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2024-04-13 16:11:33,069 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2024-04-13 16:11:33,069 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_seed_random - wb: [644] 25 bytes
2024-04-13 16:11:33,070 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_seed_random (recursive=False)
2024-04-13 16:11:33,071 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_seed_random (recursive=False)
2024-04-13 16:11:33,072 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_seed_random'>)
2024-04-13 16:11:33,072 - cc_seed_random.py[DEBUG]: no command provided
2024-04-13 16:11:33,072 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2024-04-13 16:11:33,072 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2024-04-13 16:11:33,072 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2024-04-13 16:11:33,072 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7efce5f35d00>)
2024-04-13 16:11:33,072 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2024-04-13 16:11:33,073 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2024-04-13 16:11:33,073 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2024-04-13 16:11:33,073 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2024-04-13 16:11:33,073 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_write_files - wb: [644] 25 bytes
2024-04-13 16:11:33,074 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_write_files (recursive=False)
2024-04-13 16:11:33,075 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_write_files (recursive=False)
2024-04-13 16:11:33,076 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_write_files'>)
2024-04-13 16:11:33,076 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2024-04-13 16:11:33,076 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2024-04-13 16:11:33,076 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2024-04-13 16:11:33,076 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2024-04-13 16:11:33,076 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_write_metadata - wb: [644] 25 bytes
2024-04-13 16:11:33,077 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_write_metadata (recursive=False)
2024-04-13 16:11:33,078 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_write_metadata (recursive=False)
2024-04-13 16:11:33,079 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_write_metadata'>)
2024-04-13 16:11:33,079 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 12 bytes
2024-04-13 16:11:33,087 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-04-13 16:11:33,089 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-04-13 16:11:33,089 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2024-04-13 16:11:33,090 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2024-04-13 16:11:33,090 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-04-13 16:11:33,091 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-04-13 16:11:33,091 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2024-04-13 16:11:33,092 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2024-04-13 16:11:33,092 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2024-04-13 16:11:33,092 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2024-04-13 16:11:33,092 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7efce5f35f10>)
2024-04-13 16:11:33,092 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2024-04-13 16:11:33,092 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:33,109 - util.py[DEBUG]: Reading from /proc/1451/mountinfo (quiet=False)
2024-04-13 16:11:33,109 - util.py[DEBUG]: Read 2927 bytes from /proc/1451/mountinfo
2024-04-13 16:11:33,110 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2024-04-13 16:11:33,110 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2024-04-13 16:11:33,110 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2024-04-13 16:11:33,110 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2024-04-13 16:11:33,116 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:33,242 - util.py[DEBUG]: resize_devices took 0.133 seconds
2024-04-13 16:11:33,242 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2024-04-13 16:11:33,243 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2024-04-13 16:11:33,243 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2024-04-13 16:11:33,243 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2024-04-13 16:11:33,243 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7efce5f35d00>)
2024-04-13 16:11:33,243 - util.py[DEBUG]: Reading from /proc/1451/mountinfo (quiet=False)
2024-04-13 16:11:33,244 - util.py[DEBUG]: Read 2927 bytes from /proc/1451/mountinfo
2024-04-13 16:11:33,244 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2024-04-13 16:11:33,244 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2024-04-13 16:11:33,246 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:33,245 - util.py[DEBUG]: Forked child 1584 who will run callback log_time
2024-04-13 16:11:33,256 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2024-04-13 16:11:33,256 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2024-04-13 16:11:33,256 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2024-04-13 16:11:33,257 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2024-04-13 16:11:33,257 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_disk_setup - wb: [644] 24 bytes
2024-04-13 16:11:33,259 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_disk_setup (recursive=False)
2024-04-13 16:11:33,261 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_disk_setup (recursive=False)
2024-04-13 16:11:33,261 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_disk_setup'>)
2024-04-13 16:11:33,262 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2024-04-13 16:11:33,262 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2024-04-13 16:11:33,262 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2024-04-13 16:11:33,262 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_mounts - wb: [644] 25 bytes
2024-04-13 16:11:33,263 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_mounts (recursive=False)
2024-04-13 16:11:33,264 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_mounts (recursive=False)
2024-04-13 16:11:33,264 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_mounts'>)
2024-04-13 16:11:33,264 - cc_mounts.py[DEBUG]: mounts configuration is []
2024-04-13 16:11:33,265 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2024-04-13 16:11:33,265 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2024-04-13 16:11:33,265 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2024-04-13 16:11:33,265 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2024-04-13 16:11:33,265 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2024-04-13 16:11:33,265 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2024-04-13 16:11:33,265 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2024-04-13 16:11:33,265 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2024-04-13 16:11:33,265 - cc_mounts.py[DEBUG]: changed default device swap => None
2024-04-13 16:11:33,265 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2024-04-13 16:11:33,265 - cc_mounts.py[DEBUG]: no need to setup swap
2024-04-13 16:11:33,266 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2024-04-13 16:11:33,266 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2024-04-13 16:11:33,266 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2024-04-13 16:11:33,266 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2024-04-13 16:11:33,266 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7efce5f75940>)
2024-04-13 16:11:33,267 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2024-04-13 16:11:33,267 - util.py[DEBUG]: Read 91 bytes from /var/lib/cloud/data/set-hostname
2024-04-13 16:11:33,267 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2024-04-13 16:11:33,267 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2024-04-13 16:11:33,267 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2024-04-13 16:11:33,267 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2024-04-13 16:11:33,267 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7efce5f35f10>)
2024-04-13 16:11:33,267 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-9-28.eu-central-1.compute.internal (ip-172-31-9-28)
2024-04-13 16:11:33,268 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:33,276 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-9-28.eu-central-1.compute.internal in 1 files
2024-04-13 16:11:33,276 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 44 bytes
2024-04-13 16:11:33,277 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-04-13 16:11:33,279 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-04-13 16:11:33,280 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2024-04-13 16:11:33,280 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2024-04-13 16:11:33,280 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2024-04-13 16:11:33,280 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7efce5f35b50>)
2024-04-13 16:11:33,280 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2024-04-13 16:11:33,280 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2024-04-13 16:11:33,280 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2024-04-13 16:11:33,281 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2024-04-13 16:11:33,281 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ca_certs - wb: [644] 25 bytes
2024-04-13 16:11:33,282 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ca_certs (recursive=False)
2024-04-13 16:11:33,283 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ca_certs (recursive=False)
2024-04-13 16:11:33,283 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ca_certs'>)
2024-04-13 16:11:33,283 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2024-04-13 16:11:33,283 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2024-04-13 16:11:33,283 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2024-04-13 16:11:33,284 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2024-04-13 16:11:33,284 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_rsyslog - wb: [644] 25 bytes
2024-04-13 16:11:33,285 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_rsyslog (recursive=False)
2024-04-13 16:11:33,285 - util.py[DEBUG]: backgrounded Resizing took 0.039 seconds
2024-04-13 16:11:33,306 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_rsyslog (recursive=False)
2024-04-13 16:11:33,306 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_rsyslog'>)
2024-04-13 16:11:33,307 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2024-04-13 16:11:33,307 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2024-04-13 16:11:33,307 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2024-04-13 16:11:33,307 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2024-04-13 16:11:33,307 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_selinux - wb: [644] 25 bytes
2024-04-13 16:11:33,308 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_selinux (recursive=False)
2024-04-13 16:11:33,309 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_selinux (recursive=False)
2024-04-13 16:11:33,310 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_selinux'>)
2024-04-13 16:11:33,317 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2024-04-13 16:11:33,317 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2024-04-13 16:11:33,317 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2024-04-13 16:11:33,317 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2024-04-13 16:11:33,317 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2024-04-13 16:11:33,317 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2024-04-13 16:11:33,317 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2024-04-13 16:11:33,318 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2024-04-13 16:11:33,318 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_users_groups - wb: [644] 24 bytes
2024-04-13 16:11:33,319 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_users_groups (recursive=False)
2024-04-13 16:11:33,326 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_users_groups (recursive=False)
2024-04-13 16:11:33,327 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_users_groups'>)
2024-04-13 16:11:33,328 - __init__.py[INFO]: User ec2-user already exists, skipping.
2024-04-13 16:11:33,328 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:33,392 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2024-04-13 16:11:33,404 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2024-04-13 16:11:33,406 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2024-04-13 16:11:33,407 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2024-04-13 16:11:33,416 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2024-04-13 16:11:33,417 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2024-04-13 16:11:33,417 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2024-04-13 16:11:33,417 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2024-04-13 16:11:33,418 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ssh - wb: [644] 25 bytes
2024-04-13 16:11:33,419 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ssh (recursive=False)
2024-04-13 16:11:33,420 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ssh (recursive=False)
2024-04-13 16:11:33,421 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ssh'>)
2024-04-13 16:11:33,422 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:33,458 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-04-13 16:11:33,476 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:33,485 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-04-13 16:11:33,493 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2024-04-13 16:11:33,494 - util.py[DEBUG]: Read 131 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2024-04-13 16:11:33,494 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2024-04-13 16:11:33,494 - util.py[DEBUG]: Read 211 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2024-04-13 16:11:33,494 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-04-13 16:11:33,506 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-04-13 16:11:33,507 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2024-04-13 16:11:33,507 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2024-04-13 16:11:33,508 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-04-13 16:11:33,508 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-04-13 16:11:33,509 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-04-13 16:11:33,509 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2024-04-13 16:11:33,509 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2024-04-13 16:11:33,509 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2024-04-13 16:11:33,509 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-04-13 16:11:33,509 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-04-13 16:11:33,510 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-04-13 16:11:33,510 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2024-04-13 16:11:33,512 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-04-13 16:11:33,512 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-04-13 16:11:33,512 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-04-13 16:11:33,514 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-04-13 16:11:33,514 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-04-13 16:11:33,515 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-04-13 16:11:33,515 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2024-04-13 16:11:33,515 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2024-04-13 16:11:33,515 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2024-04-13 16:11:33,515 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-04-13 16:11:33,515 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-04-13 16:11:33,526 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-04-13 16:11:33,526 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-04-13 16:11:33,528 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2024-04-13 16:11:33,528 - main.py[DEBUG]: Ran 17 modules with 0 failures
2024-04-13 16:11:33,529 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp6rx3tc03) - w: [644] 484 bytes/chars
2024-04-13 16:11:33,529 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-04-13 16:11:33,529 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2024-04-13 16:11:33,529 - util.py[DEBUG]: cloud-init mode 'init' took 2.006 seconds (2.01)
2024-04-13 16:11:33,529 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2024-04-13 16:11:34,477 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Sat, 13 Apr 2024 16:11:34 +0000. Up 9.06 seconds.
2024-04-13 16:11:34,486 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,487 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,489 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,490 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,496 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,496 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,506 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,506 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,509 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,509 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,516 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,516 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,519 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,519 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,536 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,536 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,538 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,539 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,546 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:34,546 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:34,548 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-04-13 16:11:34,549 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2024-04-13 16:11:34,549 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2024-04-13 16:11:34,549 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2024-04-13 16:11:34,550 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_keyboard - wb: [644] 25 bytes
2024-04-13 16:11:34,552 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_keyboard (recursive=False)
2024-04-13 16:11:34,555 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_keyboard (recursive=False)
2024-04-13 16:11:34,566 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_keyboard'>)
2024-04-13 16:11:34,566 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2024-04-13 16:11:34,566 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2024-04-13 16:11:34,566 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2024-04-13 16:11:34,567 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2024-04-13 16:11:34,567 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_locale - wb: [644] 25 bytes
2024-04-13 16:11:34,568 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_locale (recursive=False)
2024-04-13 16:11:34,569 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_locale (recursive=False)
2024-04-13 16:11:34,569 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_locale'>)
2024-04-13 16:11:34,569 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-04-13 16:11:34,569 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-04-13 16:11:34,570 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2024-04-13 16:11:34,570 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-04-13 16:11:34,570 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-04-13 16:11:34,570 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2024-04-13 16:11:34,573 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-04-13 16:11:34,576 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-04-13 16:11:34,576 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2024-04-13 16:11:34,577 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2024-04-13 16:11:34,577 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2024-04-13 16:11:34,577 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_set_passwords - wb: [644] 25 bytes
2024-04-13 16:11:34,578 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_set_passwords (recursive=False)
2024-04-13 16:11:34,579 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_set_passwords (recursive=False)
2024-04-13 16:11:34,579 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_set_passwords'>)
2024-04-13 16:11:34,579 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2024-04-13 16:11:34,609 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-04-13 16:11:34,609 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-04-13 16:11:34,610 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2024-04-13 16:11:34,610 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2024-04-13 16:11:34,610 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2024-04-13 16:11:34,610 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2024-04-13 16:11:34,610 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2024-04-13 16:11:34,611 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_yum_variables - wb: [644] 25 bytes
2024-04-13 16:11:34,612 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_yum_variables (recursive=False)
2024-04-13 16:11:34,613 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_yum_variables (recursive=False)
2024-04-13 16:11:34,614 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_yum_variables'>)
2024-04-13 16:11:34,614 - cc_yum_variables.py[INFO]: handling yum-variables
2024-04-13 16:11:34,614 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.4, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2024-04-13 16:11:34,614 - cc_yum_variables.py[INFO]: No yum vars to delete
2024-04-13 16:11:34,614 - cc_yum_variables.py[INFO]: No yum vars to set
2024-04-13 16:11:34,614 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2024-04-13 16:11:34,614 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2024-04-13 16:11:34,614 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2024-04-13 16:11:34,615 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_yum_add_repo - wb: [644] 25 bytes
2024-04-13 16:11:34,615 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_yum_add_repo (recursive=False)
2024-04-13 16:11:34,626 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_yum_add_repo (recursive=False)
2024-04-13 16:11:34,627 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_yum_add_repo'>)
2024-04-13 16:11:34,627 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2024-04-13 16:11:34,627 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2024-04-13 16:11:34,627 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2024-04-13 16:11:34,627 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2024-04-13 16:11:34,628 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ntp - wb: [644] 23 bytes
2024-04-13 16:11:34,628 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ntp (recursive=False)
2024-04-13 16:11:34,629 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ntp (recursive=False)
2024-04-13 16:11:34,630 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_ntp'>)
2024-04-13 16:11:34,630 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2024-04-13 16:11:34,630 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2024-04-13 16:11:34,630 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2024-04-13 16:11:34,630 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2024-04-13 16:11:34,630 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_timezone - wb: [644] 25 bytes
2024-04-13 16:11:34,631 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_timezone (recursive=False)
2024-04-13 16:11:34,632 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_timezone (recursive=False)
2024-04-13 16:11:34,633 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_timezone'>)
2024-04-13 16:11:34,633 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2024-04-13 16:11:34,633 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2024-04-13 16:11:34,633 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2024-04-13 16:11:34,633 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2024-04-13 16:11:34,633 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fb6380dc310>)
2024-04-13 16:11:34,633 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2024-04-13 16:11:34,633 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2024-04-13 16:11:34,633 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2024-04-13 16:11:34,634 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2024-04-13 16:11:34,634 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_runcmd - wb: [644] 25 bytes
2024-04-13 16:11:34,634 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_runcmd (recursive=False)
2024-04-13 16:11:34,635 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_runcmd (recursive=False)
2024-04-13 16:11:34,646 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-05efeb4cc0bcba815/sem/config_runcmd'>)
2024-04-13 16:11:34,646 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2024-04-13 16:11:34,646 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2024-04-13 16:11:34,646 - main.py[DEBUG]: Ran 9 modules with 0 failures
2024-04-13 16:11:34,647 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp64fy5iyo) - w: [644] 512 bytes/chars
2024-04-13 16:11:34,647 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-04-13 16:11:34,647 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2024-04-13 16:11:34,647 - util.py[DEBUG]: cloud-init mode 'modules' took 0.347 seconds (0.35)
2024-04-13 16:11:34,647 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2024-04-13 16:11:35,432 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Sat, 13 Apr 2024 16:11:35 +0000. Up 9.99 seconds.
2024-04-13 16:11:35,434 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-04-13 16:11:35,435 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-04-13 16:11:35,438 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-04-13 16:11:35,439 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2024-04-13 16:11:35,439 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2024-04-13 16:11:35,439 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7fa785466f40>)
2024-04-13 16:11:35,439 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2024-04-13 16:11:53,082 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2024-04-13 16:11:53,082 - main.py[DEBUG]: Ran 1 modules with 0 failures
2024-04-13 16:11:53,083 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpn47dysy4) - w: [644] 540 bytes/chars
2024-04-13 16:11:53,083 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp9ubakr8a) - w: [644] 64 bytes/chars
2024-04-13 16:11:53,083 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2024-04-13 16:11:53,084 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-04-13 16:11:53,084 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-04-13 16:11:53,084 - util.py[DEBUG]: cloud-init mode 'modules' took 17.858 seconds (16.22)
2024-04-13 16:11:53,084 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
